"""empty message

Revision ID: 30ce9afd7415
Revises: f57ecb6210ae
Create Date: 2021-11-03 11:14:03.240511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ce9afd7415'
down_revision = 'f57ecb6210ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pokemon_name', table_name='pokemon')
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=False)
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.create_index('ix_pokemon_name', 'pokemon', ['name'], unique=False)
    # ### end Alembic commands ###
