"""empty message

Revision ID: f57ecb6210ae
Revises: 752171a9161d
Create Date: 2021-11-03 10:13:23.271784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57ecb6210ae'
down_revision = '752171a9161d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('ability', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_pokemon_name'), 'pokemon', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_name'), table_name='pokemon')
    op.drop_column('pokemon', 'ability')
    # ### end Alembic commands ###
